# Generated by Django 4.0.6 on 2022-10-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apparts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apparts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('contenu', models.FileField(upload_to='Document')),
                ('objet', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.BooleanField()),
            ],
            options={
                'db_table': 'courrier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Habilitation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'habilitation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_enreg', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organisme',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeHabilitation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'type_habilitation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=150)),
                ('grade', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dateenreg', models.DateField(auto_now_add=True, db_column='dateEnreg')),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('statuts', models.CharField(blank=True, max_length=15, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.utilisateur')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.courrier')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.users')),
            ],
            options={
                'db_table': 'traffic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HabilitationApparts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_apparts', models.ForeignKey(blank=True, db_column='id_apparts', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.apparts')),
                ('id_habilitation', models.ForeignKey(blank=True, db_column='id_habilitation', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.habilitation')),
                ('id_organisme', models.ForeignKey(blank=True, db_column='id_organisme', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.organisme')),
            ],
            options={
                'db_table': 'habilitation_apparts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='habilitation',
            name='type_habilitation',
            field=models.ForeignKey(blank=True, db_column='type_habilitation', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.typehabilitation'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.users'),
        ),
        migrations.CreateModel(
            name='Appartuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_appart', models.ForeignKey(blank=True, db_column='id_appart', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.apparts')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.users')),
            ],
            options={
                'db_table': 'appartuser',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='apparts',
            name='organisme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.organisme'),
        ),
    ]
