# Generated by Django 4.0.6 on 2022-10-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
