# Generated by Django 4.0.6 on 2022-10-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.traffic'),
        ),
    ]
