# Generated by Django 4.0.6 on 2022-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_traffic_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='destination',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
