# Generated by Django 4.0.6 on 2022-10-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_courrier_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='categorie',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
