# Generated by Django 4.0.6 on 2022-10-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_courrier_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.courrier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.users')),
            ],
        ),
    ]
