# Generated by Django 4.0.6 on 2022-10-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='contenu',
            field=models.FileField(default='pas de contenu', upload_to='Annotation'),
            preserve_default=False,
        ),
    ]
