# Generated by Django 4.0.6 on 2022-10-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_annotation_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.users'),
        ),
    ]
